#!/usr/bin/env python

import sys

from rqt_dr_single.dr_single import DrSingle
from rqt_gui.main import Main

plugin = 'rqt_dr_single'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
